# Generated by Django 5.2.1 on 2026-05-12 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0005_academicyear_assignment_academic_year_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_title", models.CharField(default="Quarterly Grade Report", max_length=200)),
                ("display_name", models.CharField(blank=True, max_length=200)),
                ("quarter_1", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("quarter_2", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("quarter_3", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("quarter_4", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("final_grade", models.CharField(blank=True, max_length=50)),
                ("remarks", models.TextField(blank=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="grade_reports/logos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_reports",
                        to="hub.academicyear",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_reports",
                        to="accounts.user",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_grade_reports",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "unique_together": (("student", "teacher", "academic_year"),),
            },
        ),
    ]
