# Generated by Django 5.2.1 on 2026-05-12 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_grade_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='letter_grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('F', 'F')], max_length=2),
        ),
    ]
