# Generated by Django 6.0.4 on 2026-05-17 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0007_submission_letter_grade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolFormContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("SF1", "School Register"),
                            ("SF2", "Daily Attendance"),
                            ("SF3", "Books Issued"),
                            ("SF4", "Monthly Learner Movement"),
                            ("SF5", "Report on Promotion"),
                            ("SF6", "Summarized Report on Promotion"),
                            ("SF7", "School Personnel Assignment"),
                            ("SF8", "Learner Basic Health Profile"),
                        ],
                        max_length=3,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "content",
                    models.TextField(help_text="Rich text content of the form"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hub.academicyear",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("form_type", "teacher", "academic_year")},
            },
        ),
    ]
