# Generated by Django 5.2.1 on 2026-05-18 16:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0008_schoolformcontent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="academic_year",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="academic_year",
        ),
        migrations.AlterUniqueTogether(
            name="gradereport",
            unique_together={("student", "teacher")},
        ),
        migrations.AlterUniqueTogether(
            name="schoolformcontent",
            unique_together={("form_type", "teacher")},
        ),
        migrations.RemoveField(
            model_name="gradereport",
            name="academic_year",
        ),
        migrations.RemoveField(
            model_name="schoolformcontent",
            name="academic_year",
        ),
        migrations.DeleteModel(
            name="AcademicYear",
        ),
    ]
