# Generated by Django 5.2.1 on 2026-05-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecord",
            name="status",
            field=models.CharField(
                choices=[("present", "Present"), ("absent", "Absent")],
                default="present",
                max_length=10,
            ),
        ),
    ]
